-- MySQL Script generated by MySQL Workbench
-- Sun Oct 20 01:15:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emp_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emp_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emp_manager` DEFAULT CHARACTER SET utf8 ;
USE `emp_manager` ;

-- -----------------------------------------------------
-- Table `emp_manager`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emp_manager`.`User` ;

CREATE TABLE IF NOT EXISTS `emp_manager`.`User` (
  `UserId` VARCHAR(40) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` BLOB NULL,
  `PasswordSalt` BLOB NULL,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `SoftDeleted` TINYINT NOT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `emp_manager`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emp_manager`.`Task` ;

CREATE TABLE IF NOT EXISTS `emp_manager`.`Task` (
  `TaskId` VARCHAR(40) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `EstimatedTime` INT NULL,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UserId` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`TaskId`),
  INDEX `fk_Task_User_idx` (`UserId` ASC),
  CONSTRAINT `fk_Task_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `emp_manager`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emp_manager`.`Timesheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emp_manager`.`Timesheet` ;

CREATE TABLE IF NOT EXISTS `emp_manager`.`Timesheet` (
  `TimesheetId` VARCHAR(40) NOT NULL,
  `StartDate` DATE NOT NULL,
  `StartTime` VARCHAR(45) NOT NULL,
  `EndDate` DATE NOT NULL,
  `EndTime` VARCHAR(45) NOT NULL,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TaskId` VARCHAR(40) NOT NULL,
  `UserId` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`TimesheetId`),
  INDEX `fk_Timesheet_Task1_idx` (`TaskId` ASC),
  INDEX `fk_Timesheet_User1_idx` (`UserId` ASC),
  CONSTRAINT `fk_Timesheet_Task1`
    FOREIGN KEY (`TaskId`)
    REFERENCES `emp_manager`.`Task` (`TaskId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Timesheet_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `emp_manager`.`User` (`UserId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
